// let animals= [{
//         cuts: {
//             rib: {info:"",
//                   picture:""}, 
//             chuck: {info:"",
//                     picture:""}, 
//             brisket: {info:"",
//                       picture:""}, 
//             plate: {info:"",
//                     picture:""},
//             sirloin: {info:"",
//                       picture:""}, 
//             topsirloin: {info:"",
//                          picture:""}, 
//             tenderloin: {info:"",
//                          picture:""}, 
//             flank: {info:"",
//                     picture:""}, 
//             bottomsirloin: {info:"",
//                             picture:""}, 
//             rounds: {info:"",
//                      picture:""}, 
//             shank: {info:"",
//                      picture:""}, 
//             shortloin: {info:"",
//                         picture:""},
//         },
//         //{ cut: 'Rib', info: '', use: '' }
//     },
//     pork: {},
//     chicken: {}
// }],