const mooSVG = [
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
{/*insert SVG elements here*/ },
];